version: '3.6'

services:
  pullum-pristini-postgres:
    env_file: .env
    container_name: pullum-pristini-postgres
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - "./postgresql-multi-db.sh:/docker-entrypoint-initdb.d/postgresql-multi-db.sh"
  pgadmin:
    env_file: .env
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - pullum-pristini-postgres
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
    links:
      - "pullum-pristini-postgres:pullum-pristini-postgres"
